version: '3.9'

services:
    api: &api
        image: replicated-log:latest
        ports:
            - '4000:8000'
        networks:
            - replicated_log_network
        env_file:
            - .env.master
        links:
            - replica1
            - replica2
    replica1: &replica
        image: replicated-log:latest
        networks:
            - replicated_log_network
        ports:
            - '4001:8000'
        env_file:
            - .env.secondary
    replica2:
        <<: *replica
        ports:
            - '4002:8000'

networks:
    replicated_log_network:
